### ISSUE TITLE
Module not found: cannot resolve 'drizzle-orm/sqlite-proxy'

### ISSUE THREAD

**Issue by georg-stone** [mwufi/mac-editor#1]
This editor looks interesting, so I cloned the repo and ran it on my computer. Upon running the code, it returns:

Module not found: Can't resolve 'drizzle-orm/sqlite-proxy'

It seems as if the `drizzle-orm` package is not included in the package.json file by default.

**Comment by mwufi** [comment]
thanks for fixing this!
